### PR TITLE
upload files

### PR DESCRIPTION
**Pull request by samaracanjura**

### CODE REVIEW

**Review by jennaleonard — APPROVED** [review]
This looks good!

**Review by jennaleonard — APPROVED** [review]
.DS_Store was deleted in an attempt to resolve conflicts.

**Comment by jennaleonard** [comment]
Needed to resolve .DS_Store conflict.

**Comment by samaracanjura** [comment]
Let's see if this works :)

**Comment by samaracanjura** [comment]
let see if this works

**Pull request merged**
